### ISSUE TITLE
Add option to allow running completely from command lind

### ISSUE THREAD

**Issue by Doelfke** [buildium/generator-angular-browserify#11]
This will allow us to build tooling around it, by avoiding prompts.

For example: yo angular-browserify:component my-new-component C:\mydir

**Comment by mndewitt** [comment]
This will be possible with the component generator in v0.3.3 - I'm going to keep this open because we should do this for the page and service generators as well...

**Comment by mndewitt** [comment]
this is set for pages, services, and components.  I'm closing this for now...
